In [1]:
import pandas as pd
import numpy as np
import time
import pymysql
from sshtunnel import SSHTunnelForwarder
import matplotlib.pyplot as plt

### Loading mysql config

In [2]:
mysql_configure = pd.read_csv("Y:/Yuan/temp/mysql_connection.csv",index_col=0)

In [3]:
sql_hostname = mysql_configure.loc["sql_hostname",]["value"]
sql_username = mysql_configure.loc["sql_username",]["value"]
sql_password = mysql_configure.loc["sql_password",]["value"]
sql_main_database = mysql_configure.loc["sql_main_database",]["value"]
sql_port = mysql_configure.loc["sql_port",]["value"]
ssh_host = mysql_configure.loc["ssh_host",]["value"]
ssh_user = mysql_configure.loc["ssh_user",]["value"]
ssh_password = mysql_configure.loc["ssh_password",]["value"]
ssh_port = mysql_configure.loc["ssh_port",]["value"]

In [7]:
with SSHTunnelForwarder(
        (ssh_host, int(ssh_port)),
        ssh_username=ssh_user,
        ssh_password=ssh_password,
        remote_bind_address=('127.0.0.1', int(sql_port))) as tunnel:
    print('SSH connected')
    conn = pymysql.connect(host='127.0.0.1', user=sql_username,
            passwd=sql_password, db=sql_main_database,
            port=tunnel.local_bind_port)
    try:
        with conn as cursor: #auto commit; no close() called
            with cursor: # close() called here
                sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s "
                sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1=s.Seq and da.Res_1 = \"SER\" and da.Res_2 = \"HIS\";"    
                sql = sql_select+sql_where
                data = pd.read_sql_query(sql, conn)

    except Exception as e: # catch exceptions
        print("~~~~~~~~~~~~~~")
        print(e)
    finally:
        if conn:
            conn.close()

SSH connected

### Utils for data queries

In [59]:
def Two_active_residues_retrieval(residue_1,residue_2):
    data, data_1, data_2 = None, None, None
    with SSHTunnelForwarder(
        (ssh_host, int(ssh_port)),
        ssh_username=ssh_user,
        ssh_password=ssh_password,
        remote_bind_address=('127.0.0.1', int(sql_port))) as tunnel:
            print('SSH connected')
            conn = pymysql.connect(host='127.0.0.1', user=sql_username,
                    passwd=sql_password, db=sql_main_database,
                    port=tunnel.local_bind_port)
            try:
                with conn as cursor: #auto commit; no close() called
                    with cursor: # close() called here
                        sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s,pdbdb.Site s2 "
                        sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1=s.Seq and da.Res_1 = \"{}\" and da.pdbID = s2.pdbID and da.chain = s2.chain and da.ID_2=s2.Seq and da.Res_2 = \"{}\" ;".format(residue_1,residue_2)    
                        sql = sql_select+sql_where
                        data_1 = pd.read_sql_query(sql, conn)
                        sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s, pdbdb.Site s2 "
                        sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1=s.Seq and da.Res_1 = \"{}\" and da.pdbID = s2.pdbID and da.chain = s2.chain and da.ID_2=s2.Seq and da.Res_2 = \"{}\" ;".format(residue_2,residue_1)    
                        sql = sql_select+sql_where
                        data_2 = pd.read_sql_query(sql, conn)                        
                        data = pd.concat([data_1,data_2])
                    
            except Exception as e: # catch exceptions
                print("~~~~~~~~~~~~~~")
                print(e)
            finally:
                if conn:
                    conn.close()
    return(data)

def Two_nonactive_residues_retrieval(residue_1,residue_2):
    data, data_1, data_2 = None, None, None
    with SSHTunnelForwarder(
        (ssh_host, int(ssh_port)),
        ssh_username=ssh_user,
        ssh_password=ssh_password,
        remote_bind_address=('127.0.0.1', int(sql_port))) as tunnel:
            print('SSH connected')
            conn = pymysql.connect(host='127.0.0.1', user=sql_username,
                    passwd=sql_password, db=sql_main_database,
                    port=tunnel.local_bind_port)
            try:
                with conn as cursor: #auto commit; no close() called
                    with cursor: # close() called here
                        sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s,pdbdb.Site s2 "
                        sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1 != s.Seq and da.Res_1 = \"{}\" and da.pdbID = s2.pdbID and da.chain = s2.chain and da.ID_2 != s2.Seq and da.Res_2 = \"{}\" ;".format(residue_1,residue_2)    
                        sql = sql_select+sql_where
                        data_1 = pd.read_sql_query(sql, conn)
                        sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s, pdbdb.Site s2 "
                        sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1 != s.Seq and da.Res_1 = \"{}\" and da.pdbID = s2.pdbID and da.chain = s2.chain and da.ID_2 != s2.Seq and da.Res_2 = \"{}\" ;".format(residue_2,residue_1)    
                        sql = sql_select+sql_where
                        data_2 = pd.read_sql_query(sql, conn)                        
                        data = pd.concat([data_1,data_2])
                    
            except Exception as e: # catch exceptions
                print("~~~~~~~~~~~~~~")
                print(e)
            finally:
                if conn:
                    conn.close()
    return(data)

def Active_nonactive_residues_retrieval(residue_1,residue_2):
    data, data_1, data_2 = None, None, None
    with SSHTunnelForwarder(
        (ssh_host, int(ssh_port)),
        ssh_username=ssh_user,
        ssh_password=ssh_password,
        remote_bind_address=('127.0.0.1', int(sql_port))) as tunnel:
            print('SSH connected')
            conn = pymysql.connect(host='127.0.0.1', user=sql_username,
                    passwd=sql_password, db=sql_main_database,
                    port=tunnel.local_bind_port)
            try:
                with conn as cursor: #auto commit; no close() called
                    with cursor: # close() called here
                        sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s,pdbdb.Site s2 "
                        sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1 = s.Seq and da.Res_1 = \"{}\" and da.pdbID = s2.pdbID and da.chain = s2.chain and da.ID_2 != s2.Seq and da.Res_2 = \"{}\" ;".format(residue_1,residue_2)    
                        sql = sql_select+sql_where
                        data_1 = pd.read_sql_query(sql, conn)
                        sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s, pdbdb.Site s2 "
                        sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1 != s.Seq and da.Res_1 = \"{}\" and da.pdbID = s2.pdbID and da.chain = s2.chain and da.ID_2 = s2.Seq and da.Res_2 = \"{}\" ;".format(residue_2,residue_1)    
                        sql = sql_select+sql_where
                        data_2 = pd.read_sql_query(sql, conn)                        
                        data = pd.concat([data_1,data_2])
                    
            except Exception as e: # catch exceptions
                print("~~~~~~~~~~~~~~")
                print(e)
            finally:
                if conn:
                    conn.close()
    return(data)

def Nonactive_active_residues_retrieval(residue_1,residue_2):
    data, data_1, data_2 = None, None, None
    with SSHTunnelForwarder(
        (ssh_host, int(ssh_port)),
        ssh_username=ssh_user,
        ssh_password=ssh_password,
        remote_bind_address=('127.0.0.1', int(sql_port))) as tunnel:
            print('SSH connected')
            conn = pymysql.connect(host='127.0.0.1', user=sql_username,
                    passwd=sql_password, db=sql_main_database,
                    port=tunnel.local_bind_port)
            try:
                with conn as cursor: #auto commit; no close() called
                    with cursor: # close() called here
                        sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s,pdbdb.Site s2 "
                        sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1 != s.Seq and da.Res_1 = \"{}\" and da.pdbID = s2.pdbID and da.chain = s2.chain and da.ID_2 = s2.Seq and da.Res_2 = \"{}\" ;".format(residue_1,residue_2)    
                        sql = sql_select+sql_where
                        data_1 = pd.read_sql_query(sql, conn)
                        sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s, pdbdb.Site s2 "
                        sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1 = s.Seq and da.Res_1 = \"{}\" and da.pdbID = s2.pdbID and da.chain = s2.chain and da.ID_2 != s2.Seq and da.Res_2 = \"{}\" ;".format(residue_2,residue_1)    
                        sql = sql_select+sql_where
                        data_2 = pd.read_sql_query(sql, conn)                        
                        data = pd.concat([data_1,data_2])
                    
            except Exception as e: # catch exceptions
                print("~~~~~~~~~~~~~~")
                print(e)
            finally:
                if conn:
                    conn.close()
    return(data)

def Two_all_residues_retrieval(residue_1,residue_2):
    data, data_1, data_2 = None, None, None
    with SSHTunnelForwarder(
        (ssh_host, int(ssh_port)),
        ssh_username=ssh_user,
        ssh_password=ssh_password,
        remote_bind_address=('127.0.0.1', int(sql_port))) as tunnel:
            print('SSH connected')
            conn = pymysql.connect(host='127.0.0.1', user=sql_username,
                    passwd=sql_password, db=sql_main_database,
                    port=tunnel.local_bind_port)
            try:
                with conn as cursor: #auto commit; no close() called
                    with cursor: # close() called here
                        sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s,pdbdb.Site s2 "
                        sql_where = "WHERE da.Res_1 = \"{}\" and da.Res_2 = \"{}\" ;".format(residue_1,residue_2)    
                        sql = sql_select+sql_where
                        data_1 = pd.read_sql_query(sql, conn)
                        sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s, pdbdb.Site s2 "
                        sql_where = "WHERE da.Res_1 = \"{}\" andda.Res_2 = \"{}\" ;".format(residue_2,residue_1)    
                        sql = sql_select+sql_where
                        data_2 = pd.read_sql_query(sql, conn)                        
                        data = pd.concat([data_1,data_2])
                    
            except Exception as e: # catch exceptions
                print("~~~~~~~~~~~~~~")
                print(e)
            finally:
                if conn:
                    conn.close()
    return(data)



def Two_residues_generic_retrieval(residue_1,residue_2,active_1,active_2):
    data, data_1, data_2 = None, None, None
    with SSHTunnelForwarder(
        (ssh_host, int(ssh_port)),
        ssh_username=ssh_user,
        ssh_password=ssh_password,
        remote_bind_address=('127.0.0.1', int(sql_port))) as tunnel:
            print('SSH connected')
            conn = pymysql.connect(host='127.0.0.1', user=sql_username,
                    passwd=sql_password, db=sql_main_database,
                    port=tunnel.local_bind_port)
            try:
                with conn as cursor: #auto commit; no close() called
                    with cursor: # close() called here
                        
                        #not pairewise anymore
#                         sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s,pdbdb.Site s2 "
#                         sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1 {} s.Seq and da.Res_1 = \"{}\" and da.pdbID = s2.pdbID and da.chain = s2.chain and da.ID_2 {} s2.Seq and da.Res_2 = \"{}\" ;".format(active_1,residue_1,active_2,residue_2)    
#                         sql = sql_select+sql_where
#                         data_1 = pd.read_sql_query(sql, conn)
#                         sql_select = "Select da.* FROM pdbdb.Distance_angle da, pdbdb.Site s, pdbdb.Site s2 "
#                         sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1 {} s.Seq and da.Res_1 = \"{}\" and da.pdbID = s2.pdbID and da.chain = s2.chain and da.ID_2 {} s2.Seq and da.Res_2 = \"{}\" ;".format(active_2,residue_2,active_1,residue_1)    
#                         sql = sql_select+sql_where
#                         data_2 = pd.read_sql_query(sql, conn)                        
#                         data = pd.concat([data_1,data_2])
                        sql_select = "Select da.* FROM pdbdb.`Distance_angle2.0` da, pdbdb.Site s,pdbdb.Site s2 "
                        sql_where = "WHERE da.pdbID = s.pdbID and da.chain = s.chain and da.ID_1 {} s.Seq and da.Res_1 = \"{}\" and da.pdbID = s2.pdbID and da.chain = s2.chain and da.ID_2 {} s2.Seq and da.Res_2 = \"{}\" ;".format(active_1,residue_1,active_2,residue_2)    
                        sql = sql_select+sql_where
                        data_1 = pd.read_sql_query(sql, conn)
                        data = data_1

                    
            except Exception as e: # catch exceptions
                print("~~~~~~~~~~~~~~")
                print(e)
            finally:
                if conn:
                    conn.close()
    return(data)

In [148]:
active_data = Two_residues_generic_retrieval("HIS","SER","!=","!=")
active_data = active_data[active_data["Distance"]<17]

SSH connected

In [ ]:
aminoAcidCodes = ["ALA","ARG","ASN","ASP","CYS","GLN","GLY","GLU","HIS","ILE","LEU","LYS",
                 "MET","PHE","PRO","SER","THR","TRP","TYR","VAL"]
for i in range(len(aminoAcidCodes)):
    for j in range(i,len(aminoAcidCodes)):
        residue_1 = aminoAcidCodes[i]
        residue_2 = aminoAcidCodes[j]

        fig, axs = plt.subplots(4, 2,figsize=(10,5))
        fig.suptitle('{} and {}'.format(residue_1,residue_2))

        active_data = Two_residues_generic_retrieval(residue_1,residue_2,"=","=")
        active_data = active_data[active_data["Distance"]<17]
        axs[0,0].scatter(active_data["Distance"],active_data["Angle"],marker = "s")
        axs[0,1].hist([float(x) for x in active_data["Angle"]], bins=20,range=(0,180)) 

        active_data = Two_residues_generic_retrieval(residue_1,residue_2,"!=","!=")
        active_data = active_data[active_data["Distance"]<17]
        axs[1,0].scatter(active_data["Distance"],active_data["Angle"],marker = "s")
        axs[1,1].hist([float(x) for x in active_data["Angle"]], bins=20,range=(0,180))

        active_data = Two_residues_generic_retrieval(residue_1,residue_2,"=","!=")
        active_data = active_data[active_data["Distance"]<17]
        axs[2,0].scatter(active_data["Distance"],active_data["Angle"],marker = "s")
        axs[2,1].hist([float(x) for x in active_data["Angle"]], bins=20,range=(0,180))

        active_data = Two_residues_generic_retrieval(residue_1,residue_2,"!=","=")
        active_data = active_data[active_data["Distance"]<17]
        axs[3,0].scatter(active_data["Distance"],active_data["Angle"],marker = "s")
        axs[3,1].hist([float(x) for x in active_data["Angle"]], bins=20,range=(0,180))

        #Two_all_residues_retrieval(residue_1,residue_2)
        #active_data = active_data[active_data["Distance"]<17]
        #axs[4,0].scatter(active_data["Distance"],active_data["Angle"],marker = "s")
        #axs[4,1].hist([float(x) for x in active_data["Angle"]], bins=20,range=(0,180))        
                
        fig.savefig("Y:/Yuan/temp/Two_way_plots/{}_and_{}".format(residue_1,residue_2))
        plt.show()

##  Catorgory of amino acids
### Amino Acids with Hydrophobic Side Chain – Aliphatic
Alanine, Ala, A; Isoleucine, ile, l; Leucine, Leu, L; Methionine, Met, M; Valine, Val,V
### Amino Acids with Hydrophobic Side Chain – Aromatic
Phenylalanine, Phe, F; Tryptophan, Trp, W; Tyrosine, Tyr, Y
### Amino Acids with Polar Neutral Side Chains
Asparagine, Asn, N; Cysteine, Cys, C; Glutamine, Gln, Q; Serine, Ser, S; Threonine, Thr, T
### Amino Acids with Electrically Charged Side Chains – Acidic
Asparic acid, Asp, D; Glutamic Glu, E
### Amino Acids with Electrically Charged Side Chains – Basic
Arginine, Arg,R; Histidine, His, H, Lysine, Lys, K
### Unique Amino Acids
Glycine, Gly, G; Proline, Pro, P

#### Source:https://www.sigmaaldrich.com/life-science/metabolomics/learning-center/amino-acid-reference-chart.html

In [31]:
amino_acid_property_by_res = {"ALA":1,"ILE":1,"LEU":1,"MET":1,"VAL":1,
                      "PHE":2, "TRP":2,"TYR":2,
                       "ASN":3,"CYS":3,"GLN":3,"SER":3,"THR":3,
                      "ASP":4,"GLU":4,"ARG":5,"HIS":5,"LYS":5,"GLY":6,"PRO":6}
amino_acid_property_by_type = {1:["ALA","ILE","LEU","MET","VAL"],
                               2:["PHE","TRP","TYR"],3:["ASN","CYS","GLN","SER","THR"],
                               4:["ASP","GLU"],5:["ARG","HIS","LYS"],6:["GLY","PRO"]}

In [ ]:
aminoAcidCodes = ["ALA","ARG","ASN","ASP","CYS","GLN","GLY","GLU","HIS","ILE","LEU","LYS",
                 "MET","PHE","PRO","SER","THR","TRP","TYR","VAL"]
for i in range(len(aminoAcidCodes)):
    for j in range(i,len(aminoAcidCodes)):
        residue_1 = aminoAcidCodes[i]
        residue_2 = aminoAcidCodes[j]

        fig, axs = plt.subplots(4, 2,figsize=(10,5))
        fig.suptitle('{} and {}'.format(residue_1,residue_2))

        active_data = Two_residues_generic_retrieval(residue_1,residue_2,"=","=")
        active_data = active_data[active_data["Distance"]<17]
        axs[0,0].scatter(active_data["Distance"],active_data["Angle"],marker = "s")
        axs[0,1].hist([float(x) for x in active_data["Angle"]], bins=20,range=(0,180)) 

        active_data = Two_residues_generic_retrieval(residue_1,residue_2,"!=","!=")
        active_data = active_data[active_data["Distance"]<17]
        axs[1,0].scatter(active_data["Distance"],active_data["Angle"],marker = "s")
        axs[1,1].hist([float(x) for x in active_data["Angle"]], bins=20,range=(0,180))

        active_data = Two_residues_generic_retrieval(residue_1,residue_2,"=","!=")
        active_data = active_data[active_data["Distance"]<17]
        axs[2,0].scatter(active_data["Distance"],active_data["Angle"],marker = "s")
        axs[2,1].hist([float(x) for x in active_data["Angle"]], bins=20,range=(0,180))

        active_data = Two_residues_generic_retrieval(residue_1,residue_2,"!=","=")
        active_data = active_data[active_data["Distance"]<17]
        axs[3,0].scatter(active_data["Distance"],active_data["Angle"],marker = "s")
        axs[3,1].hist([float(x) for x in active_data["Angle"]], bins=20,range=(0,180))

        fig.savefig("Y:/Yuan/temp/Two_way_plots/{}_and_{}".format(residue_1,residue_2))
        plt.show()

In [ ]:
for i in range(1,7):
    for j in range(1,7):
        type_one = amino_acid_property_by_type[i]
        type_two = amino_acid_property_by_type[j]
        fig.suptitle('{} and {}'.format(str(i),str(j)))
        fig, axs = plt.subplots(4, 2,figsize=(10,5))
        
        plot_data = pd.DataFrame()
        for res_1 in type_one:
            for res_2 in type_two:
                active_data = Two_residues_generic_retrieval(res_1,res_2,"=","=")
                active_data = active_data[(active_data["Distance"]<17)&(active_data["Distance"]>0)]
                print(active_data.shape)
                plot_data = pd.concat([active_data,plot_data])
        
        axs[0,0].scatter(plot_data["Distance"],plot_data["Angle"],marker = "s")
        axs[0,1].hist([float(x) for x in plot_data["Angle"]], bins=20,range=(0,180)) 
        
        plot_data = pd.DataFrame()
        for res_1 in type_one:
            for res_2 in type_two:
                active_data = Two_residues_generic_retrieval(res_1,res_2,"!=","!=")
                active_data = active_data[(active_data["Distance"]<17)&(active_data["Distance"]>0)]
                print(active_data.shape)
                plot_data = pd.concat([active_data,plot_data])
        
        axs[1,0].scatter(plot_data["Distance"],plot_data["Angle"],marker = "s")
        axs[1,1].hist([float(x) for x in plot_data["Angle"]], bins=20,range=(0,180)) 

        plot_data = pd.DataFrame()
        for res_1 in type_one:
            for res_2 in type_two:
                active_data = Two_residues_generic_retrieval(res_1,res_2,"=","!=")
                active_data = active_data[(active_data["Distance"]<17)&(active_data["Distance"]>0)]
                print(active_data.shape)
                plot_data = pd.concat([active_data,plot_data])
        
        axs[2,0].scatter(plot_data["Distance"],plot_data["Angle"],marker = "s")
        axs[2,1].hist([float(x) for x in plot_data["Angle"]], bins=20,range=(0,180))
        
        plot_data = pd.DataFrame()
        for res_1 in type_one:
            for res_2 in type_two:
                active_data = Two_residues_generic_retrieval(res_1,res_2,"!=","=")
                active_data = active_data[(active_data["Distance"]<17)&(active_data["Distance"]>0)]
                print(active_data.shape)
                plot_data = pd.concat([active_data,plot_data])
        
        axs[3,0].scatter(plot_data["Distance"],plot_data["Angle"],marker = "s")
        axs[3,1].hist([float(x) for x in plot_data["Angle"]], bins=20,range=(0,180))
        
        fig.savefig("Y:/Yuan/temp/Two_way_plots/{}_and_{}".format(str(i),str(j)))
        plt.show()

In [62]:
plot_data

          ID pdbID chain ID_1 Res_1 ID_2 Res_2  Distance  Angle
0     506427  1b65     A  289   GLY  289   GLY       0.0    0.0
1     818209  1azw     A   43   GLY   43   GLY       0.0    0.0
2    1252859  1fy2     A   88   GLY   88   GLY       0.0    0.0
3    3705054  1k32     A  918   GLY  918   GLY       0.0    0.0
4    4024907  1ssx     A  193   GLY  193   GLY       0.0    0.0
5    4570143  1pq5     A  193   GLY  193   GLY       0.0    0.0
6    4784584  1rtf     B  193   GLY  193   GLY       0.0    0.0
7    4844447  1qrz     A  742   GLY  742   GLY       0.0    0.0
8    4955577  1tyf     A   68   GLY   68   GLY       0.0    0.0
9    5037089  1rgq     A  140   GLY  140   GLY       0.0    0.0
10   5310853  1cqq     A  145   GLY  145   GLY       0.0    0.0
11   5562124  1cvr     A  212   GLY  212   GLY       0.0    0.0
12   6411770  1qx3     A  122   GLY  122   GLY       0.0    0.0
13   6464754  1qtn     A  350   GLY  350   GLY       0.0    0.0
14   6491849  1nw9     B  238   GLY  238   GLY       0.0    0.0
15   6677168  1a30     A   27   GLY   27   GLY       0.0    0.0
16  10171199  1ryp     I   47   GLY   47   GLY       0.0    0.0